USE [master]
GO
/****** Object:  Database [rsff_UnitTesting]    Script Date: 04/17/2015 09:53:46 ******/
CREATE DATABASE [rsff_UnitTesting] ON  PRIMARY 
( NAME = N'rsff_UnitTesting', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\rsff_UnitTesting.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'rsff_UnitTesting_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\rsff_UnitTesting_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [rsff_UnitTesting] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rsff_UnitTesting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [rsff_UnitTesting] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET ANSI_NULLS OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET ANSI_PADDING OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET ARITHABORT OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [rsff_UnitTesting] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [rsff_UnitTesting] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [rsff_UnitTesting] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET  DISABLE_BROKER
GO
ALTER DATABASE [rsff_UnitTesting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [rsff_UnitTesting] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [rsff_UnitTesting] SET  READ_WRITE
GO
ALTER DATABASE [rsff_UnitTesting] SET RECOVERY FULL
GO
ALTER DATABASE [rsff_UnitTesting] SET  MULTI_USER
GO
ALTER DATABASE [rsff_UnitTesting] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [rsff_UnitTesting] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'rsff_UnitTesting', N'ON'
GO
USE [rsff_UnitTesting]
GO
/****** Object:  StoredProcedure [dbo].[up_Project_Get_Count]    Script Date: 04/17/2015 09:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[up_Project_Get_Count]
AS
Select COUNT(*) from Rsff.Dbo.Projects
WHERE IsDeleted = 0
GO
/****** Object:  StoredProcedure [dbo].[up_Parcel_Get_Count]    Script Date: 04/17/2015 09:53:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[up_Parcel_Get_Count]
AS
Select COUNT(*) from Rsff.Dbo.Parcels
WHERE IsDeleted = 0
GO
